### PR TITLE
e2e: Fix Rclone privileged test

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
The rclone tests (privileged and unprivileged) were using the same s3 path, causing a race. This was only noticeable for the priv test because that one was preserving the UID of the files.

Also:
- Dumps logs from the "helper tools" roles pods.
- Backs out ignoring the mismatches of UIDs (#494)

**Is there anything that requires special attention?**

**Related issues:**
Reverts #494

### CODE REVIEW

**Comment by JohnStrunk** [comment]
/hold
Need to remove the last commit before merging. It's just there for debugging.

**Comment by JohnStrunk** [comment]
/unhold
/test all
/cc @tesshuflower

The failures we had been seeing were due to the 2 rclone tests using the came object bucket, not a code or OpenShift artifact.  It was a race.

**Review by tesshuflower — APPROVED** [review]
/lgtm

**Comment by JohnStrunk** [comment]
/retest
seems to be a bad day for launching clusters

**Pull request merged**
