### PR TITLE
Update changelog and helm for 0.5.0 release

### PR DESCRIPTION
**Pull request by tesshuflower**
Signed-off-by: Tesshu Flower <tflower@redhat.com>

**Describe what this PR does**
Updates changelog and helm charts so we can make the 0.5.0 release

**Is there anything that requires special attention?**

- This will need to be cherry-picked into the `release-0.5` branch.
- Not sure I got everything in the changelog - anything I missed?

**Related issues:**

### CODE REVIEW

**Comment by tesshuflower** [comment]
/cc @JohnStrunk 

Seems like the e2e failed trying to remove the default storageclass annotation on gp2, but I thought that was removed?

**Comment by JohnStrunk** [comment]
I forgot to update the fips test. ☹️

**Comment by tesshuflower** [comment]
> I forgot to update the fips test. ☹️

Ah, that makes sense then, no problem - I made a PR here:  https://github.com/openshift/release/pull/32299

**Review by JohnStrunk — COMMENTED** [review]
How about adding (under added):
```
New data mover based on Syncthing for live data synchronization
```

**Pull request merged**
