### PR TITLE
Changelog updates for v0.7.0

### PR DESCRIPTION
**Pull request by tesshuflower**
**Describe what this PR does**

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Review by birsanv — APPROVED** [review]
lgtm

**Comment by onedr0p** [comment]
It looks like the helm chart for this version is missing. Was there a problem during release?

**Comment by tesshuflower** [comment]
@onedr0p The 0.7.0 helm charts have now been published.

**Comment by onedr0p** [comment]
Thank you so much @tesshuflower !

**Pull request merged**
