### PR TITLE
Upgrade operator-sdk 1.9.0 ==> 1.14.0

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
This upgrades the operator-sdk scaffolding from 1.9 to 1.14.

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by JohnStrunk** [comment]
/cc @tesshuflower 

`ci/prow/unit` needs to be updated to work with the new way envtest is being installed/used by the latest sdk versions. I'll work on that next.

**Review by tesshuflower — APPROVED** [review]
LGTM!

**Pull request merged**
