### PR TITLE
feat: add source and destination support for nfs volumes

### PR DESCRIPTION
**Pull request by onedr0p**
Signed-off-by: Devin Buhl <devin@buhl.casa>

**Describe what this PR does**

Adds support to mount a NFS volume as the data volume in the data mover pods.

I have implemented this in all of the movers, let me know what you all think and I can update the docs on the rest of the movers.

**Is there anything that requires special attention?**

I have not fully tested this other than it building and running. I am interested in feedback. One thing to observe is that the `/data` mount point in the data mover pods is a "local" volume, so should we be overriding the `RESTIC_REPOSITORY` to `/data` when the nfs options are set in the config?

**Related issues:**

https://github.com/backube/volsync/issues/319

### CODE REVIEW

**Comment by JohnStrunk** [comment]
@onedr0p Thanks for filing the issue and posting a PR.
Some thoughts:
- Since this is only applicable to the restic mover, I'd like to limit the changes to that portion of the code.
- I'd also like to have this be more generic by just referencing a PVC name instead of NFS directly.

Based on the above, you could add the following to `ReplicationDestinationResticSpec`
```go
	// repositoryPVC is the name of an existing PVC containing the backup repository
	//+optional
	RepositoryPVC string `json:"repositoryPVC,omitempty"`
```

Then in the restic mover controller, if RepostoryPVC is filled in, it can be added as a volume mount on `/repository`, allowing the restic Secret to refer to that "local" path.

**Comment by onedr0p** [comment]
Hi @JohnStrunk thanks for the feedback, I agree with you on all points.

My only thought would be could it be possible to use the same NFS PVC for all applications? For example say I have 3 applications I want backed up using restic, could I reuse the same PVC and just point each to `/repository/<app-name>` in the CR?

Small background, I was able to use [Kyverno and have it create cronjobs for backing up PVCs with a certain label to a Kopia repository](https://github.com/onedr0p/home-ops/blob/main/cluster/apps/kyverno/policies/snapshot-cronjob-controller.yaml). After doing this, I discovered volsync and really loved the simplicity of this project and would love to integrate Kopia #320 as a data mover here as well. I was thinking too fork volsync and have it match my usecase but I'm pretty happy with your progress and diligence so far.

**Comment by JohnStrunk** [comment]
Since the (NFS) PVC would be RWX, use by multiple (mover) pods simultaneously would be fine. You'd just need to have a unique restic Secret per ReplicationSource that holds the sub-path (`/repository/subpath`) for each source that you want to back up.

Glad you find the project useful. :heart:

**Comment by onedr0p** [comment]
Closing this PR as I haven't had time to get back to it. Maybe someday I can get back to hacking at it.

**Pull request closed without merging**
