### PR TITLE
update cust scorecard config to use release-0.6 tags

### PR DESCRIPTION
**Pull request by tesshuflower**
Signed-off-by: Tesshu Flower <tflower@redhat.com>

**Describe what this PR does**
- Updates custom scorecard config.yaml to use the custom-scorecard image for release-0.6.  Needed as the one in main (i.e. latest) will eventually diverge.

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by tesshuflower** [comment]
This probably won't work until a fix is done to the Auto Generated Files Check - attempting a fix in: https://github.com/backube/volsync/pull/524

**Comment by tesshuflower** [comment]
@JohnStrunk I'm seeing e2e tests failing occasionally, especially with syncthing - however haven't found much in the logs - syncthing movers appear to be starting ok, but I see the replicationsource status hasn't been updated yet as the api is seeing connection refused - not sure if this is just a matter of it taking longer than the timeout to come up the 1st time?

**Comment by JohnStrunk** [comment]
I've been noticing a lot of failures in kind as well. I'm wondering if all the tests running at once is overloading the GH actions runner. Perhaps I should refresh #409 and see if that helps anything.

**Review by JohnStrunk — COMMENTED** [review]
/lgtm

**Pull request merged**
