### PR TITLE
PRs that have "hold" label should not be marked stale

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by tesshuflower** [comment]
@JohnStrunk This PR seems to be stuck, not sure how to get it to re-run the failed jobs - what do you think about force-merging it?  We don't really need the e2e to run anyway for this change.

**Comment by JohnStrunk** [comment]
done :smile_cat:

**Pull request merged**
