### PR TITLE
Update readthedocs config to use python 3.11

### PR DESCRIPTION
**Pull request by tesshuflower**
See: https://github.com/readthedocs/readthedocs.org/issues/10290

**Describe what this PR does**

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by JohnStrunk** [comment]
I can't seem to trigger the actions workflow for the operator build. I think you're going to need to re-push now that GH has recovered.

**Comment by tesshuflower** [comment]
I think I'm going to have to re-push again to force the operator tests to run and report status - they seem to have gotten lost

**Review by JohnStrunk — COMMENTED** [review]
GitHub has been having a bad week. :cry:
/lgtm

**Pull request merged**
