### PR TITLE
CI: Adjust test timeouts

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
Adjusts step timeouts to try and get the e2e tests passing more consistently. We don't seem to be running into any actual failures, just timeouts due to not waiting long enough.

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by JohnStrunk** [comment]
/hold
Still doing more testing...

**Review by tesshuflower — APPROVED** [review]
/lgtm

**Pull request merged**
