### PR TITLE
Remove kuttl tests

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
Now that all the e2e tests have been moved to ansible, we don't need kuttl any more. This removes kuttl and the kuttl-based tests.

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by JohnStrunk** [comment]
/cc @tesshuflower 
OpenShift e2e is broken w/ this change since it still expects kuttl to be there.

**Review by tesshuflower — APPROVED** [review]
/lgtm

**Comment by JohnStrunk** [comment]
e2e fix will be in openshift/release#31509

**Pull request merged**
