### PR TITLE
feat: expose `last` on `retain` options for restic mover

### PR DESCRIPTION
**Pull request by onedr0p**
**Describe what this PR does**

Allows users to set `last` as forget option in the ReplicationDestination  CR.

**Is there anything that requires special attention?**

I believe I hit all the right spots in the code as the functionality was mainly there just not exposed as an option.

**Related issues:**

https://github.com/backube/volsync/issues/557

### CODE REVIEW

**Comment by tesshuflower** [comment]
@JohnStrunk what do you think about allowing restic keep-last?  Let me know if you're ok with this one and I could help add a unit test as well.

**Comment by JohnStrunk** [comment]
My concern with this is if the backup portion succeeds, but something else (like the forget) fails such that the operator thinks the container failed. This can cause the operator to loop, retrying backups. The result could end up being a large number of backups in rapid succession.
"keep last" would cause the older backups to get purged, leaving the user with all backups from approximately the same time.
This is why I didn't enable it originally.

Having said that, the current structure of the restic script makes that fairly unlikely since all it does is a forget right after the backup.

Honestly, I'm on the fence w/ whether to take this because it's dangerous for the user, in a way that isn't obvious.

**Comment by JohnStrunk** [comment]
This also needs a `make generate` added to the commit to fix the failed test

**Comment by tesshuflower** [comment]
fixed the make generate, but I do think @JohnStrunk your concerns are valid about potentially losing older snapshots unintentionally.

**Comment by onedr0p** [comment]
> This can cause the operator to loop, retrying backups. The result could end up being a large number of backups in rapid succession.

I've seen then happen on my end but maybe it's worth putting in the docs to use `last` only with another type like `daily` so that at least if the backup loop happens at least `daily` will be retained?

**Comment by onedr0p** [comment]
@JohnStrunk with that said if `last` is supported and the backup loop happens at last it won't flood the restic repo with hundreds or more snapshots.

**Pull request merged**
