### PR TITLE
Update tool/lib versions

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
Updates the versions of the tools we use:
- helm: 3.6.3
- operator-sdk: 1.10.1
  - 1.10.0 -> 1.10.1 required upgrades to some of the scaffolding
- kuttl: 0.11.1
- rclone: 1.56.0
- restic: 0.12.1

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by JohnStrunk** [comment]
I suspect this is a problem w/ the Go version used in CI and the changes to envtest in controller-runtime.
The current version of envtest imports `io/fs` which is new in Go 1.16. f33 installs 1.15 :cry:, so this PR is going to require changes to the openshift-ci configuration.

**Comment by JohnStrunk** [comment]
/hold

New versions of SDK and golangci-lint are out

**Comment by cooktheryan** [comment]
@JohnStrunk feel free to ping me when you get SDK and golang-lint versions bumped

**Comment by JohnStrunk** [comment]
This is being handled by #100 and #103, plus changes to the openshift CI configuration.

/close

**Pull request closed without merging**
