### PR TITLE
Unit test fix - cleanup SCC crd in-between tests

### PR DESCRIPTION
**Pull request by tesshuflower**
Signed-off-by: Tesshu Flower <tflower@redhat.com>

**Describe what this PR does**
Tries to reduce errors with unit tests where sccs could be left behind when the next test in the same process starts.

**Related issues:**
Fixes: https://github.com/backube/volsync/issues/514

### CODE REVIEW

**Comment by JohnStrunk** [comment]
@tesshuflower After you fix the conflict, is this ready for review?

**Comment by tesshuflower** [comment]
> @tesshuflower After you fix the conflict, is this ready for review?

yes, this should be ready to go - let me do that now

**Pull request merged**
