### PR TITLE
changelog update for 0.5.1

### PR DESCRIPTION
**Pull request by tesshuflower**
Signed-off-by: Tesshu Flower <tflower@redhat.com>

**Describe what this PR does**
Update the list of fixed items that will go into the 0.5.1 release

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by tesshuflower** [comment]
@JohnStrunk interesting, looks like markdownlint is failing here on a few .md files - I think because the unordered list indentation has been changed to 3 from 2:  https://github.com/markdownlint/markdownlint/pull/373

**Comment by JohnStrunk** [comment]
> @JohnStrunk interesting, looks like markdownlint is failing here on a few .md files - I think because the unordered list indentation has been changed to 3 from 2: [markdownlint/markdownlint#373](https://github.com/markdownlint/markdownlint/pull/373)

Ugh... That's horrible.

What do you think about just adding the rule changes to [.ci-scripts/mdl-style.rb](https://github.com/backube/volsync/blob/main/.ci-scripts/mdl-style.rb) to set it back to 2:  
https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md007---unordered-list-indentation

**Comment by tesshuflower** [comment]
/cc @JohnStrunk 

Thx for re-running the failed test

**Review by JohnStrunk — COMMENTED** [review]
/lgtm

**Pull request merged**
