### PR TITLE
Add design doc for RWO mover affinity

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
Provides a design for how we can run movers against live RWO volumes (no clone/snapshot)

**Is there anything that requires special attention?**

**Related issues:**
Design for: #17

### CODE REVIEW

**Comment by JohnStrunk** [comment]
/hold
Would like to hear some feedback on this.
Build version: https://volsync--222.org.readthedocs.build/en/222/design/rwo-affinity.html

**Review by tesshuflower — APPROVED** [review]
/lgtm

Sorry, it slipped my mind to do this earlier after our meeting

**Pull request merged**
