### PR TITLE
Return status info from movers

### PR DESCRIPTION
**Pull request by tesshuflower**
**Describe what this PR does**
Adds status.latestMoverStatus which will attempt to capture parts of the latest mover job logs (applicable to rsync, rsync-tls, rclone, restic atm).

**Is there anything that requires special attention?**

- Currently each mover has its own filter function to filter lines
   - These filter on a line-by-line basis - but we could pass the entire log as well if more complex filtering is required
- Current log filters are only selecting specific lines, not modifying the lines themselves - this could be improved if we want to change what we save to the log.
   - Filters themselves also can be tuned if we want to log less/more or capture specific outputs - examples with expected outputs can be see in the logfilter_test.go files for each mover.
   - On job failures (i.e. error scenario), the movers are currently saving the entire log.  Generally these are short, but not sure if there are scenarios where the error log could be long
- Using env vars right now to allow overrides of the max number of lines to tail from the job pod and a debug mode to allow saving the entire log - Is this ok?

Here's an example of status in a replicationsource (latestMoverStatus is new):
```
status:
  conditions:
  - lastTransitionTime: "2023-01-11T16:59:04Z"
    message: Waiting for manual trigger
    reason: WaitingForManual
    status: "False"
    type: Synchronizing
  lastManualSync: once
  lastSyncDuration: 1m22.766397s
  lastSyncTime: "2023-01-11T16:59:04Z"
  latestMoverStatus:
    logs: |-
      no parent snapshot found, will read all files
      Added to the repository: 929 B (691 B stored)
      processed 1 files, 5 B in 0:00
      snapshot 062534bc saved
      Restic completed in 8s
    result: Successful
  restic: {}
```

**Related issues:**
https://github.com/backube/volsync/issues/538

### CODE REVIEW

**Comment by tesshuflower** [comment]
/cc @JohnStrunk 

Do you mind taking a look and see what you think?

**Comment by JohnStrunk** [comment]
I'm ok with the approach of putting a few log lines into the status on success. The error path causes me concern though...
Right now, we're not bounding the about of data that we could try to shove into the status. Large objects can hurt etcd performance... There's also a maximum size.

At a minimum, we need to put a limit on the size. It would be great if we could do the same regex thing for failures, but I don't have a good way to figure out what the possible (important) error strings would be.

**Comment by tesshuflower** [comment]
> I'm ok with the approach of putting a few log lines into the status on success. The error path causes me concern though... Right now, we're not bounding the about of data that we could try to shove into the status. Large objects can hurt etcd performance... There's also a maximum size.
> 
> At a minimum, we need to put a limit on the size. It would be great if we could do the same regex thing for failures, but I don't have a good way to figure out what the possible (important) error strings would be.

Agreed - I'll put in another field (with a reasonably small default) for the max size we'll log to the status - we could still combine this with regex filters for error scenarios if we find some that give us the relevant data.

@JohnStrunk Are you ok with these values getting set by env vars on the volsync operator?

**Pull request merged**
