### PR TITLE
Remove the old CLI

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
- Removes the code for the old CLI.

The new CLI now has feature parity w/ the old, so the old one can be removed. Documentation had been removed previously.

**Is there anything that requires special attention?**

**Related issues:**
Fixes: #155 
Blocked by:
- #141 
- #157

### CODE REVIEW

**Comment by JohnStrunk** [comment]
/hold

Pending dependent PRs

**Comment by JohnStrunk** [comment]
/unhold
/cc @tesshuflower 
/assign @tesshuflower 

The blocking PRs have merged, so this is ready

**Review by tesshuflower — APPROVED** [review]
/lgtm

**Pull request merged**
