### PR TITLE
Upgrade operator-sdk to v1.22.0

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
Upgrades scaffolding to sdk 1.22

**Is there anything that requires special attention?**
This looks like it's starting to scaffold some of the new security stuff that we're going to need to address soon.

**Related issues:**

### CODE REVIEW

**Review by tesshuflower — COMMENTED** [review]
I think we may need to make sure the crds in bundle/manifests are also updated to be in-sync with the ones in `crd/bases`.  Running `make bundle` will probably take care of this.

**Comment by JohnStrunk** [comment]
Good catch

**Comment by JohnStrunk** [comment]
/retest
That's a strange unit test failure (etcd timeout)

**Pull request merged**
