### PR TITLE
CLI: replication schedule & sync

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
Adds operations for the CLI replication sub-command to handle setting the replication schedule as well as triggering a manual sync.

**Is there anything that requires special attention?**

**Related issues:**
Blocked by #126

### CODE REVIEW

**Comment by JohnStrunk** [comment]
e2e on openshift is failing because we're not building the CLI there: openshift/release#26551
/hold

**Comment by JohnStrunk** [comment]
> What is the important of yaml files in `test-kuttl/e2e/` ? How `e2e` testing is done through these yaml files ?

The e2e tests are driven by [kuttl](https://kuttl.dev/docs/). Invocation is via [`make test-e2e`](https://github.com/backube/volsync/blob/14be83df1df958215a47e0bb7c612ba9e9961741/Makefile#L112-L114). It assumes a cluster is available, VolSync is installed, and Minio is available in-cluster for the rclone and restic tests.

The tests live in subdirectories under `test-kuttl`. Currently there's just `e2e` which are general e2e operator tests. This PR adds a directory to collect tests for the CLI. Each test has it's own subdir, and the test steps are executed in the order determined by their numeric prefix--- optional test step, followed by an optional assert. (See details in the kuttl docs)

**Review by v-harihar — APPROVED** [review]
/lgtm

**Comment by JohnStrunk** [comment]
@v-harihar rebased

**Review by tesshuflower — APPROVED** [review]
/lgtm

**Pull request merged**
