### PR TITLE
Uppdate k8s.io/utils digest to 3b25d92

### PR DESCRIPTION
**Pull request by tesshuflower**
- move to k8s.io/utils/ptr instead of deprecated k8s.io/utils/pointer

**Describe what this PR does**

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by tesshuflower** [comment]
/cc @JohnStrunk 

Any idea what I'm doing wrong with trying to override the sonar check?  it's flagging dup code in the various mover files since I had to touch them for this PR.

**Review by JohnStrunk — APPROVED** [review]
/lgtm

**Pull request merged**
