### PR TITLE
`go get github.com/openshift/api@release-4.13 && go mod tidy`

### PR DESCRIPTION
**Pull request by kaovilai**
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

**Describe what this PR does**

just a version upgrade corresponding to 4.13

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

**Comment by JohnStrunk** [comment]
@kaovilai Please fill out the PR template.
Specifically: what is the reason for the change? Does it fix some bug or CVE? Or is it just a version upgrade corresponding to 4.13?

**Comment by kaovilai** [comment]
just a version upgrade corresponding to 4.13.

It was bothering me we are pulling in 3.9.0 which is causing other repos when pulling volsync latest to downgrade to 3.9.0 and have to do messy replace.

**Comment by kaovilai** [comment]
One instance where 3.9.0 no longer builds.. https://github.com/openshift/oadp-operator/pull/1024#issuecomment-1555913026

**Comment by JohnStrunk** [comment]
> One instance where 3.9.0 no longer builds.. [openshift/oadp-operator#1024 (comment)](https://github.com/openshift/oadp-operator/pull/1024#issuecomment-1555913026)

I don't understand your comment. I assume you mean OCP 4.9 (aka kube 1.22) which is no longer supported on any major platform.

Are you suggesting this shouldn't be merged?

**Comment by kaovilai** [comment]
I'm saying tagged version referenced in go.mod prior to this PR to openshift/API v3.9.0 no longer builds on a new environment without local go.mod cache.

That tag no longer exists online.

**Comment by kaovilai** [comment]
This PR is still good afaik

**Pull request merged**
